#
# refers:
#     - https://learn.hashicorp.com/collections/vagrant/getting-started
#     - https://www.vagrantup.com/docs/synced-folders/basic_usage
# boxes: https://app.vagrantup.com/boxes/search
#
Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/xenial64" # LTS16.04
    #config.vm.box = "ubuntu/focal64" # LTS20.04
    
    config.vm.provider "virtualbox" do |v|
        v.memory = 8192
        v.cpus = 8
    end

    # experimental feature, need env VAGRANT_EXPERIMENTAL="disks" 
    config.vm.disk :disk, size: "100GB", primary: true

    config.vm.network "public_network"
    # config.ssh.username = 'vagrant'
    # config.ssh.password = 'vagrant'
 
    # exec while "vagrant up" "vagrant reload"
    config.vm.provision :shell, path: "bootstrap.sh"

    # ------------ file sync

    # synced folders (low-performance)
    #config.vm.synced_folder "../workspace", "/home/vagrant/workspace" 

    # rsync
    config.vm.synced_folder "../lede", "/home/vagrant/lede", 
        type: "rsync",
        rsync__exclude: [".git/", "build_dir/", "staging_dir/"],
        rsync__args: ["--archive", "--delete", "--links", "--safe-links"]

end
